I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Scripts/first_chapter/mansion_first_chapter.rpy", line 84, in script
    radolev "Так-так-так! Какие красавицы решили посетить мой сегодняшний бал!"
Exception: Sayer 'radolev' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Scripts/first_chapter/mansion_first_chapter.rpy", line 84, in script
    radolev "Так-так-так! Какие красавицы решили посетить мой сегодняшний бал!"
  File "/home/dmitrii/renpy-8.2.1-sdk/renpy/ast.py", line 2557, in execute
    Say.execute(self)
  File "/home/dmitrii/renpy-8.2.1-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/dmitrii/renpy-8.2.1-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'radolev' is not defined.

Linux-5.15.0-71-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.2.1.24030407
GlashaTest 1.0
Wed May 29 14:50:58 2024
