I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script
    Boss "..."
Exception: Sayer 'Boss' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script
    Boss "..."
  File "C:\Users\User\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\User\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\User\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Boss' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
GlashaTest 1.0
Thu Apr  4 22:12:10 2024
